### ISSUE TITLE
Percentage character in Host settings fields breaks settings saving

### ISSUE THREAD

**Issue by okuuva** [mattmattmatt/opus-pebble#37]
Opus doesn't seem to handle percentage character (%) in any of the host info fields. It just fails silently if any of the fields contain %, without saving any modifications to any of the edited fields in any of the hosts.

I generally use automatically generated passwords everywhere, including in my Kodi remote authentication. At first it seemed that the whole Opus was utterly broken, but after a bit of detective work I managed to narrow it down to the special character handling. All the other special characters in my current password were handled just fine, it was only the percentage char that caused some hick up in settings saving.

Possible duplicate: https://github.com/mattmattmatt/opus-pebble/issues/36

**Comment by mattmattmatt** [comment]
Thanks for the report, I will investigate and release a fix once verified, @okuuva.

**Comment by mattmattmatt** [comment]
This problem should now be solved as of [this commit](https://github.com/mattmattmatt/opus-pebble/commit/b00f0bdf4a7d46de11ffd8d3d36a01ed37cdc5c3) and [Opus version 2.3](https://apps.getpebble.com/en_US/application/56ac4a755319ec979400000d/changelog).

Please let me know if the problem persists in your configuration.
