### ISSUE TITLE
PBL_ROUND support?

### ISSUE THREAD

**Issue by zecoj** [mattmattmatt/opus-pebble#38]
It'd be awesome if you could make this compatible with the time round. Thanks.

**Comment by mattmattmatt** [comment]
I will do so as soon as it becomes available for Cloudpebble (which is what I use to build Opus).

Track the status of [Pebble Round support in Cloudpebble here](https://github.com/pebble/pebblejs/issues/96).

**Comment by tmikkonen** [comment]
Seems like PTR support should now be available for Cloudpebble.

**Comment by mattmattmatt** [comment]
Yep, I noticed last week. As soon as I get some time to adjust the interface elements to the round display, I'll release this Watch App also for the Pebble Time Round.

**Comment by tmikkonen** [comment]
Sweet! I'll be sure to check it out when it's released.
