### ISSUE TITLE
Request - Easy IP switch via shake.

### ISSUE THREAD

**Issue by dtw2000** [mattmattmatt/opus-pebble#40]
Would you consider adding the current IP or Host name on all your control screens, and coding a shake to automatically switch to your next host/IP?

**Comment by mattmattmatt** [comment]
I would consider adding the option to show the current host on the control screens.

I would not consider this a major use case for most users, though, so I would not sacrifice "shake to update" for "shake to circle to next host". But I'll see if I can come up with a quicker way to switch hosts.

May I ask what your setup looks like so I can better understand your need for this?

**Comment by dtw2000** [comment]
My use case is that I have 2 KODI setups in separate rooms.  I have opus as a quick launch on my pebble.  I usually have to jump a few screens to switch to the desired host, and back out to start controlling KODI.  I agree it's not a major use case.  Would you consider a "shake updates currently playing, if (nothing is currently playing & hosts > 1) then cycle host."

I did fork the project in hopes to compile a tweaked version.  So far, I haven't had much luck.  I'm having trouble getting the pebble.js library associated with the SDK on my local machine.  I switched to cloudpebble; however, when I import my fork, it seems to be building a pebble.js example rather than the opus project.  I've compiled a few basic pebble apps, both locally and using cloudpebble.  If you have an obvious insight, I'd appreciate the input.  Sorry if this is getting too far off topic.  Thank you for the app.

**Comment by dtw2000** [comment]
I was able to compile locally.  I added the host name in front of the time.  I'm not sure how to go about adding the host cycle function.  It looks like I should add it on the handler-main screen?

**Comment by mattmattmatt** [comment]
There is already a shake handler in `handler-main`: https://github.com/mattmattmatt/opus-pebble/blob/master/src/handler-main.js#L425.

You could implement a function here that depending on some condition either updates the state from the host (current behavior) or cycles to the next host.
Something like 

``` JS
mainScreen.on('accelTap', function() {
    if (somethingOrAnotherIsTrue) {
        module.exports.updatePlayerState();
    } else {
        var nextHostIndex = Settings.data('activeHostIndex')++;
        nextHostIndex = nextHostIndex > Settings.option('hosts').length - 1 ? 0 : nextHostIndex;
        var newHost = Settings.option('hosts')[nextHostIndex];
        Settings.data('activeHost', newHost);
        Settings.data('activeHostIndex', nextHostIndex);
        module.exports.reset();
        module.exports.updatePlayerState();
    }
});
```

I currently don't have time to test this but something along the lines of this should work.
Good luck! 👍

**Comment by dtw2000** [comment]
Hey, Thanks.  It is working nicely.  I uploaded the changes.  It's a bit hacky.  I wasn't sure how to change the phone app settings to do it properly with extra switches and all.  The accelTap event can easily trigger multiple times consecutively and usually triggers on a vibrate as well.  I basically used your strategy for double clicks to get it smoothed out.  Thanks again.

**Comment by mattmattmatt** [comment]
No problem, glad you got it working for yourself.

I'll close this issue for now and might take some of your ideas into the app at one point.
